### ISSUE TITLE
Laravel 8.0 release not installable

### ISSUE THREAD

**Issue by Schnoop** [langleyfoxall/laravel-nist-password-rules#32]
As php-coveralls is currently not supporting Guzzle 7.0, which is a requirement for Laravel 8.0, this package is not installable at the moment.
https://github.com/php-coveralls/php-coveralls/issues/287

**Comment by pl38** [comment]
Coveralls seems to have updated https://github.com/php-coveralls/php-coveralls/pull/288 any chance of an update as I also cannot get it to install as present.

**Comment by poseso** [comment]
Please add support to Laravel 8

**Comment by ziming** [comment]
PR #32 has been merged for paragonie/certainty. I think only @DivineOmega packages are left to support Guzzle 7, then we can upgrade to laravel 8.

Guzzle 7 is a laravel 8 requirement.

**Comment by DivineOmega** [comment]
Hi all. 

v1.1.0 of my psr-18-guzzle-adapter package has now. Hopefully Laravel 8 should now be supported.

Give it a test, and get back to me if needed.

**Comment by DivineOmega** [comment]
Closing due to lack of response.
