### ISSUE TITLE
guzzlehttp/guzzle ~7.0

### ISSUE THREAD

**Issue by abdosaeedelhassan** [langleyfoxall/laravel-nist-password-rules#33]
i have installed guzzlehttp/guzzle ~7.0, when trying to install this package i received that

  Problem 1
    - Installation request for langleyfoxall/laravel-nist-password-rules ^4.3 -> satisfiable by langleyfoxall/laravel-nist-password-rules[v4.3.0].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0) -> satisfiable by guzzlehttp/guzzle[7.0.1].

is there away to upgrade please, thank you

**Comment by Schnoop** [comment]
Not at the moment. This package depends on php-coveralls which has a requirement for guzzle version 6. So as long php-coveralls is not updated you can do nothing.

Please have a look here: https://github.com/langleyfoxall/laravel-nist-password-rules/issues/32
