### ISSUE TITLE
PHP_EOL Windows

### ISSUE THREAD

**Issue by GaraiViktor** [langleyfoxall/laravel-nist-password-rules#41]
- DictionaryWords
- RepetitiveCharacters
- SequentialCharacters

rules are won't work on windows, PHP_EOL on Windows is not "\n" but "\r\n".

The `passwords` property has incorrect value, only has one item with the full content of txt, instead of one item per row.

I have 2 suggestion:
1. change explode to preg_split. `preg_split('/\n|\r\n?/', file_get_contents(self::PASSWORDS_FILE))`
2. or just hardcode the `\n` line end character. `explode('\n', file_get_contents(self::PASSWORDS_FILE))`

**Comment by DivineOmega** [comment]
This should now be fixed: https://github.com/langleyfoxall/laravel-nist-password-rules/releases/tag/v5.0.1
