### ISSUE TITLE
Please merge pull requests

### ISSUE THREAD

**Issue by nezaboravi** [langleyfoxall/laravel-nist-password-rules#47]
Blocking us to upgrade to Laravel 9, could you please kindly merge PR?

**Comment by patricksebastien** [comment]
@langleyfoxall-access is it because this dependency not being able to bump to laravel 9?
`"divineomega/laravel-password-exposed-validation-rule": "^2.4.0"`

**Comment by LNCH** [comment]
Laravel 9 support is now merged, apologies for the delay everyone!
