### ISSUE TITLE
Laravel 9 Release

### ISSUE THREAD

**Issue by faisaljawad1** [langleyfoxall/laravel-nist-password-rules#48]
When are you planning to release support for Laravel 9.x?

**Comment by ash123456789** [comment]
Laravel 9 support will be added as soon as possible. We use this package internally on almost all of our projects so it will likely happen soon. No ETA unfortunately.

**Comment by LNCH** [comment]
@faisaljawad1 Laravel 9 support has been added, apologies for the delay.
